import { Laptop, Smartphone, Headphones, BookOpen, Shirt, Home } from "lucide-react"
import type { Product, Category, User, Comment } from "./types"

export const categories: Category[] = [
  {
    id: "1",
    name: "电子产品",
    slug: "electronics",
    icon: <Laptop className="h-6 w-6" />,
  },
  {
    id: "2",
    name: "手机",
    slug: "smartphones",
    icon: <Smartphone className="h-6 w-6" />,
  },
  {
    id: "3",
    name: "耳机",
    slug: "headphones",
    icon: <Headphones className="h-6 w-6" />,
  },
  {
    id: "4",
    name: "图书",
    slug: "books",
    icon: <BookOpen className="h-6 w-6" />,
  },
  {
    id: "5",
    name: "服装",
    slug: "clothing",
    icon: <Shirt className="h-6 w-6" />,
  },
  {
    id: "6",
    name: "家居",
    slug: "home",
    icon: <Home className="h-6 w-6" />,
  },
]

export const featuredProducts: Product[] = [
  {
    id: "1",
    name: "超薄笔记本电脑 Pro",
    description: "高性能轻薄笔记本电脑，搭载最新处理器和高清显示屏，适合工作和娱乐。",
    price: 6999,
    image: "/placeholder.svg?height=300&width=300",
    category: "electronics",
    stock: 15,
    rating: 4.5,
    reviewCount: 120,
    discount: 10,
    isNew: true,
    createdAt: "2023-05-15T08:00:00.000Z",
    features: ["最新一代处理器", "16GB 内存", "512GB SSD存储", "14英寸高清显示屏", "轻薄设计，重量仅1.2kg"],
    specifications: {
      处理器: "Intel Core i7-1165G7",
      内存: "16GB LPDDR4X",
      存储: "512GB NVMe SSD",
      显示屏: "14英寸 2K IPS",
      电池: "56Wh，最长12小时续航",
      接口: "2x USB-C, 1x USB-A, 1x HDMI",
      尺寸: "323 x 218 x 15.9 mm",
      重量: "1.2 kg",
    },
  },
  {
    id: "2",
    name: "智能手机 X Pro",
    description: "旗舰级智能手机，配备高清摄像头和强大的处理性能，为您带来卓越的移动体验。",
    price: 4999,
    image: "/placeholder.svg?height=300&width=300",
    category: "electronics",
    stock: 25,
    rating: 4.8,
    reviewCount: 230,
    discount: 0,
    isNew: true,
    createdAt: "2023-06-20T10:30:00.000Z",
    features: ["6.7英寸OLED全面屏", "1亿像素主摄", "8GB+256GB大内存", "5000mAh大电池", "支持5G网络"],
  },
  {
    id: "3",
    name: "无线降噪耳机",
    description: "高品质无线降噪耳机，提供出色的音质和舒适的佩戴体验，让您沉浸在音乐世界中。",
    price: 1299,
    image: "/placeholder.svg?height=300&width=300",
    category: "electronics",
    stock: 50,
    rating: 4.6,
    reviewCount: 180,
    discount: 15,
    isNew: false,
    createdAt: "2023-04-10T14:15:00.000Z",
  },
  {
    id: "4",
    name: "编程入门指南",
    description: "适合初学者的编程入门书籍，通过简单易懂的语言和实例，帮助您快速掌握编程基础。",
    price: 59,
    image: "/placeholder.svg?height=300&width=300",
    category: "books",
    stock: 100,
    rating: 4.3,
    reviewCount: 75,
    discount: 0,
    isNew: false,
    createdAt: "2023-03-05T09:45:00.000Z",
  },
  {
    id: "5",
    name: "商务休闲西装",
    description: "高品质商务休闲西装，采用优质面料，剪裁合体，适合各种正式场合穿着。",
    price: 899,
    image: "/placeholder.svg?height=300&width=300",
    category: "clothing",
    stock: 30,
    rating: 4.4,
    reviewCount: 65,
    discount: 20,
    isNew: false,
    createdAt: "2023-02-18T11:20:00.000Z",
  },
  {
    id: "6",
    name: "智能手表 Series 5",
    description: "功能强大的智能手表，支持健康监测、运动追踪和智能通知，是您日常生活的得力助手。",
    price: 1599,
    image: "/placeholder.svg?height=300&width=300",
    category: "electronics",
    stock: 40,
    rating: 4.7,
    reviewCount: 150,
    discount: 5,
    isNew: true,
    createdAt: "2023-07-01T16:40:00.000Z",
  },
  {
    id: "7",
    name: "人工智能与未来",
    description: "探讨人工智能发展趋势和未来影响的深度解析书籍，适合对科技前沿感兴趣的读者。",
    price: 79,
    image: "/placeholder.svg?height=300&width=300",
    category: "books",
    stock: 85,
    rating: 4.5,
    reviewCount: 60,
    discount: 0,
    isNew: true,
    createdAt: "2023-06-15T13:10:00.000Z",
  },
  {
    id: "8",
    name: "运动休闲套装",
    description: "舒适透气的运动休闲套装，适合日常运动和休闲穿着，展现活力与时尚。",
    price: 399,
    image: "/placeholder.svg?height=300&width=300",
    category: "clothing",
    stock: 60,
    rating: 4.2,
    reviewCount: 90,
    discount: 10,
    isNew: false,
    createdAt: "2023-05-05T10:30:00.000Z",
  },
  {
    id: "9",
    name: "便携蓝牙音箱",
    description: "小巧便携的蓝牙音箱，音质出色，防水设计，是户外活动和家庭聚会的理想选择。",
    price: 299,
    image: "/placeholder.svg?height=300&width=300",
    category: "electronics",
    stock: 70,
    rating: 4.4,
    reviewCount: 110,
    discount: 0,
    isNew: false,
    createdAt: "2023-04-20T15:25:00.000Z",
  },
  {
    id: "10",
    name: "经典文学全集",
    description: "收录世界经典文学作品的精装全集，是文学爱好者的珍藏之选。",
    price: 499,
    image: "/placeholder.svg?height=300&width=300",
    category: "books",
    stock: 25,
    rating: 4.9,
    reviewCount: 40,
    discount: 5,
    isNew: false,
    createdAt: "2023-03-15T12:50:00.000Z",
  },
  {
    id: "11",
    name: "时尚连衣裙",
    description: "优雅时尚的连衣裙，采用高品质面料，设计简约大方，适合各种场合穿着。",
    price: 459,
    image: "/placeholder.svg?height=300&width=300",
    category: "clothing",
    stock: 45,
    rating: 4.3,
    reviewCount: 85,
    discount: 15,
    isNew: true,
    createdAt: "2023-07-10T09:15:00.000Z",
  },
  {
    id: "12",
    name: "专业摄影相机",
    description: "高端专业摄影相机，配备先进的图像处理技术和多功能镜头，满足专业摄影需求。",
    price: 8999,
    image: "/placeholder.svg?height=300&width=300",
    category: "electronics",
    stock: 10,
    rating: 4.8,
    reviewCount: 35,
    discount: 0,
    isNew: true,
    createdAt: "2023-06-25T14:30:00.000Z",
  },
]

export const users: User[] = [
  {
    id: "1",
    name: "管理员",
    email: "admin@example.com",
    isAdmin: true,
  },
  {
    id: "2",
    name: "张三",
    email: "zhangsan@example.com",
    isAdmin: false,
  },
  {
    id: "3",
    name: "李四",
    email: "lisi@example.com",
    isAdmin: false,
  },
]

export const comments: Comment[] = [
  {
    id: "1",
    userId: "2",
    userName: "张三",
    productId: "1",
    rating: 5,
    content: "非常好用的笔记本电脑，性能强大，外观也很漂亮，推荐购买！",
    createdAt: "2023-06-20T10:30:00.000Z",
  },
  {
    id: "2",
    userId: "3",
    userName: "李四",
    productId: "1",
    rating: 4,
    content: "整体不错，就是有点贵，但是性能确实很好，续航也很长。",
    createdAt: "2023-06-25T14:15:00.000Z",
  },
  {
    id: "3",
    userId: "2",
    userName: "张三",
    productId: "2",
    rating: 5,
    content: "手机很流畅，拍照效果也很好，电池续航能力强，非常满意！",
    createdAt: "2023-07-05T09:45:00.000Z",
  },
]
